### ISSUE TITLE
Useless orderings on the Darc

### ISSUE THREAD

**Issue by vorner** [brunoczim/lockfree#1]
All the methods of Darc have the `Ordering` parameter. However, the practical effect of the parameter is basically zero (except choosing how big the performance impact is), because all the methods also contain strategically placed SeqCst atomic operations.

In the theoretical situation if it did not contain the SeqCst operations, it would actually be a soundness issue ‒ if stored an Arc with Relaxed in one thread and loaded it in another also with Relaxed, there'd be nothing synchronizing the data the Arc points to, effectively creating possible data race. Note that the `AtomicPtr` does not have this problem, because to create the data race one has to dereference the pointer ‒ but because the pointer is raw one, it is unsafe operation and therefore it is up to the user to make sure everything is OK. With Arc, dereferencing is safe so it is up to whatever gets the pointer from one thread to another to ensure there's appropriate synchronization.

**Comment by brunoczim** [comment]
>  because all the methods also contain strategically placed SeqCst atomic operations

Do you mean, the Arc by himself?

If so, would you recommend removing `Ordering`s? Because of `Arc`'s `SeqCst`, is it safe to replace the `Ordering`s with `Relaxed`?

**Comment by vorner** [comment]
Yes, I think so ‒ you need to have a „synchronization edge“ between the threads, which is provided in the incinerator SeqCst operations. Therefore, using Relaxed on the actual load is OK.

**Comment by brunoczim** [comment]
I see. Fool of me not realizing that :P

Reasoning about it, yes, `incinerator` ends up doing the needed synchronization. I intend to change `incinerator`'s Orderings to `AcqRel`, `Acquire` and `Release`, but even so `Darc` should not have public `Ordering`s.

Thanks for the help pal!
